server:
  port: 9003


#配置spring-data-jpa

spring:
  profiles: dev
  application:
    name: abcms-provider-depart
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none



  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test03?serverTimezone=UTC   #useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true



eureka:
  client:
    service-url: http://eureka8100.com:8100/eureka


---
#配置test
server:
  port: 9004
spring:
  profiles: test
  application:
    name: abcms-provider-depart


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test03?serverTimezone=UTC   #useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
  #main:
    #allow-bean-definition-overriding: true

eureka:
  client:
    service-url: http://eureka8200.com:8200/eureka