server:
  port: 7070
spring:
  profiles: dev
  application:
    name: abcms-consumer-depart
eureka:
  client:
    service-url:
    defaultZone: http://eureka8100.com:8100/eureka

feign:
  hystrix:
    enabled: true

---
server:
  port: 7071
spring:
  profiles: test
  application:
    name: abcms-consumer-depart

eureka:
  client:
    service-url:
      defaultZone: http://eureka8200.com:8200/eureka

feign:
  hystrix:
    enabled: true
